### ISSUE TITLE
Subsystem Overview

### ISSUE THREAD

**Issue by lennartweiss** [fh-erfurt/MovieStarMS#13]
a short description of the subsystems which come with the major software provided

**Comment by SirNeils** [comment]
![Screenshot (272)](https://user-images.githubusercontent.com/59617808/102286053-c3766700-3f37-11eb-8f63-301746a2b316.png)

**Comment by SirNeils** [comment]
![Screenshot (276)](https://user-images.githubusercontent.com/59617808/102344108-b5f2c880-3f9b-11eb-8104-c105b2fa8f93.png)
