### ISSUE TITLE
Website-structur through Tree-diagramm

### ISSUE THREAD

**Issue by KriXsTeR** [fh-erfurt/MovieStarMS#6]
Shows how the single sub-sites and the index-site are linked up.

**Comment by KriXsTeR** [comment]
[Flowchart - Kopie.pdf](https://github.com/fh-erfurt/MovieStarMS/files/5566848/Flowchart.-.Kopie.pdf)
Erste Struktur

**Comment by SirNeils** [comment]
![Screenshot (182)](https://user-images.githubusercontent.com/59617808/100421910-95fd7280-3089-11eb-8ad9-46156b402c82.png)

**Comment by YukiGasai** [comment]
- Sign Up 
- can return from everywhere back to homepage
- movie between today/week and ticket

**Comment by SirNeils** [comment]
![Screenshot (199)](https://user-images.githubusercontent.com/59617808/100941430-e5b0c380-34f9-11eb-961d-cceab94b7bf6.png)

any improvements?
